name: AL SaaS Unit Test Runner
description: Runs AL tests on a Business Central SaaS Sandbox environment.

inputs:
  CONTAINERNAME:
    description: 'Proxy container name (FilesOnly)'
    required: true
  TENANT_ID:
    description: 'Azure AD Tenant ID'
    required: true
  ENVIRONMENT:
    description: 'Business Central environment name'
    required: true
  REFRESH_TOKEN:
    description: 'Refresh token for authentication'
    required: true
  TEST_APP_NAME:
    description: 'Display name of the test app'
    required: true

runs:
  using: composite
  steps:
    - name: Install BcContainerHelper
      shell: pwsh
      run: |
        Install-Module BcContainerHelper -Force -AllowClobber -SkipPublisherCheck

    - name: Run Tests in SaaS Environment
      shell: pwsh
      run: |
        $authContext = New-BcAuthContext -tenantId '${{ inputs.TENANT_ID }}' -refreshToken '${{ inputs.REFRESH_TOKEN }}'
        $testApp = Get-BcInstalledExtensions -bcAuthContext $authContext -environment '${{ inputs.ENVIRONMENT }}' | Where-Object { $_.DisplayName -eq '${{ inputs.TEST_APP_NAME }}' }
        if (-not $testApp) {
          Write-Error 'Test app not found in the environment'
          exit 1
        }
        Run-TestsInBcContainer `
          -containerName '${{ inputs.CONTAINERNAME }}' `
          -bcAuthContext $authContext `
          -environment '${{ inputs.ENVIRONMENT }}' `
          -extensionId $testApp.Id `
          -detailed `
          -XUnitResultFileName "$env:GITHUB_WORKSPACE\\TestResults.xml"
