name: AL Unit Test Runner
description: Runs AL unit tests on a Business Central container and reports results

inputs:
  container-name:
    description: "Name of the Business Central container"
    required: true
  BC_USERNAME:
    description: "Business Central username"
    required: true
  BC_PASSWORD:
    description: "Business Central password"
    required: true
  Build_StagingDirectory:
    description: "Path to the build staging directory."
    required: true
runs:
  using: "composite"
  steps:
    - name: Install BcContainerHelper
      shell: powershell
      run: |
        Write-Host "Installing BcContainerHelper module..."
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module BcContainerHelper -Force -SkipPublisherCheck -AllowClobber

    - name: Check Container Status
      shell: pwsh
      run: |
        docker ps -a | Select-String '${{ inputs.container-name }}'

    - name: Ensure Test Toolkit is Installed
      shell: pwsh
      run: |
        Invoke-ScriptInBcContainer -containerName "${{ inputs.container-name }}" -scriptblock {
          $testToolkit = Get-NAVAppInfo -ServerInstance BC | Where-Object { $_.Name -eq 'Test Runner' }
          if (-not $testToolkit) {
            Write-Host "⚠️ Test Toolkit not found. Installing..."
            Import-TestToolkitToBcContainer -containerName "${{ inputs.container-name }}"
            Write-Host "✅ Test Toolkit installed successfully."
          } else {
            Write-Host "✅ Test Toolkit is already installed."
          }
        }

    - name: Publish Test App
      shell: pwsh
      run: |
        $testAppPath = Join-Path "${{ inputs.Build_StagingDirectory }}" "test.app"
        if (-not (Test-Path $testAppPath)) {
          Write-Host "❌ test.app not found!"
          exit 1
        }
        $password = ConvertTo-SecureString "${{ inputs.BC_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ("${{ inputs.BC_USERNAME }}", $password)

        Publish-BcContainerApp -containerName "${{ inputs.container-name }}" -credential $credential -appFile $testAppPath -sync -install -SkipVerification

    - name: List Available Tests
      shell: pwsh
      run: |
        $password = ConvertTo-SecureString "${{ inputs.BC_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ("${{ inputs.BC_USERNAME }}", $password)

        Write-Host "Available tests:"
        Get-TestsFromBcContainer -containerName "${{ inputs.container-name }}" -testSuite "DEFAULT" -credential $credential | Format-Table -AutoSize

    - name: Run AL Tests
      shell: pwsh
      run: |
        $password = ConvertTo-SecureString "${{ inputs.BC_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ("${{ inputs.BC_USERNAME }}", $password)

        # Önce test codeunit'inin kesin adını bulalım
        $allTests = Get-TestsFromBcContainer -containerName "${{ inputs.container-name }}" -testSuite "DEFAULT" -credential $credential
        $customerListTests = $allTests | Where-Object { $_.Name -like "*Customer List*" }
        
        if ($customerListTests) {
          $testCodeunitName = $customerListTests[0].Name
          $testCodeunitId = $customerListTests[0].Id
          Write-Host "Found test codeunit: $testCodeunitName (ID: $testCodeunitId)"
          
          # ID ile test çalıştır - Bu daha güvenilir
          $testResults = Run-TestsInBcContainer -containerName "${{ inputs.container-name }}" `
            -credential $credential -detailed -tenant default `
            -testCodeunit $testCodeunitId `
            -EnableTaskScheduler:$false `
            -XUnitResultFileName "$env:GITHUB_WORKSPACE\TestResults.xml"
        } else {
          # Eğer bulunamazsa tüm testleri çalıştır
          Write-Host "Customer List test codeunit bulunamadı. Tüm testler çalıştırılıyor..."
          $testResults = Run-TestsInBcContainer -containerName "${{ inputs.container-name }}" `
            -credential $credential -detailed -tenant default `
            -XUnitResultFileName "$env:GITHUB_WORKSPACE\TestResults.xml"
        }

        if (-not $testResults) {
          Write-Host "::warning::Test çalıştı ancak sonuç döndürmedi. Test uygulaması test fonksiyonları içeriyor mu?"
        } else {
          $successCount = ($testResults | Where-Object { $_.Result -eq "Success" }).Count
          $failureCount = ($testResults | Where-Object { $_.Result -eq "Failure" }).Count
          $skippedCount = ($testResults | Where-Object { $_.Result -eq "Skipped" }).Count
          
          Write-Host "Test sonuçları:"
          Write-Host "- Başarılı: $successCount"
          Write-Host "- Başarısız: $failureCount" 
          Write-Host "- Atlanmış: $skippedCount"
          
          if ($failureCount -gt 0) {
            Write-Host "::error::$failureCount test başarısız oldu!"
            exit 1
          } else {
            Write-Host "✅ Tests completed successfully."
          }
        }

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: al-test-results
        path: ${{ github.workspace }}/TestResults.xml
        retention-days: 30