name: AL SaaS Unit Test Runner
description: Runs AL tests on a Business Central SaaS Sandbox environment.

inputs:
  CONTAINERNAME:
    description: 'Proxy container name (FilesOnly)'
    required: true
  TENANT_ID:
    description: 'Azure AD Tenant ID'
    required: true
  ENVIRONMENT:
    description: 'Business Central environment name'
    required: true
  REFRESH_TOKEN:
    description: 'Refresh token for authentication'
    required: true
  ARTIFACTS_DIRECTORY:
    description: 'Directory where the test.app is located'
    required: true

runs:
  using: composite
  steps:
    - name: Install BcContainerHelper
      shell: pwsh
      run: |
        Install-Module BcContainerHelper -Force -AllowClobber -SkipPublisherCheck

    - name: Get Test App Display Name from .app file
      shell: pwsh
      run: |
        $testAppPath = Join-Path '${{ inputs.ARTIFACTS_DIRECTORY }}' 'test.app'
        $appInfo = Get-AppJsonFromAppFile -appFile $testAppPath
        "TEST_APP_NAME=$($appInfo.Name)" >> $env:GITHUB_ENV

    - name: Run Tests in SaaS Environment
      shell: pwsh
      run: |
        $authContext = New-BcAuthContext -tenantId '${{ inputs.TENANT_ID }}' -refreshToken '${{ inputs.REFRESH_TOKEN }}'
        $testApp = Get-BcInstalledExtensions -bcAuthContext $authContext -environment '${{ inputs.ENVIRONMENT }}' | Where-Object { $_.DisplayName -eq $env:TEST_APP_NAME }
        if (-not $testApp) {
          Write-Error "❌ Test app '$($env:TEST_APP_NAME)' not found in the environment '${{ inputs.ENVIRONMENT }}'"
          exit 1
        }
        Run-TestsInBcContainer `
          -containerName '${{ inputs.CONTAINERNAME }}' `
          -bcAuthContext $authContext `
          -environment '${{ inputs.ENVIRONMENT }}' `
          -extensionId $testApp.Id `
          -detailed `
          -XUnitResultFileName "$env:GITHUB_WORKSPACE\TestResults.xml"
