name: "AL Test Runner"
description: "Runs AL unit tests on a Business Central container"

inputs:
  container-name:
    description: "Name of the Business Central container"
    required: true
  test-suite-name:
    description: "Name of the test suite to run"
    required: false
    default: "DEFAULT"
  BC_USERNAME:
    description: "Business Central username"
    required: true
  BC_PASSWORD:
    description: "Business Central password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install BcContainerHelper (PowerShell 5.1)
      shell: powershell
      run: |
        Write-Host "Installing BcContainerHelper module..."
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module BcContainerHelper -Force -SkipPublisherCheck -AllowClobber
        Get-Module -ListAvailable BcContainerHelper

    - name: Debug Container Status
      shell: pwsh
      run: |
        Write-Host "Checking if container '${{ inputs.container-name }}' is running..."
        docker ps -a | Select-String -Pattern "${{ inputs.container-name }}"
        if ($LASTEXITCODE -ne 0) { Write-Error "::error::Container not found or not running"; exit 1 }

    - name: Run AL Tests in Container with Debug
      shell: pwsh
      env:
        BC_USERNAME: ${{ inputs.BC_USERNAME }}
        BC_PASSWORD: ${{ inputs.BC_PASSWORD }}
      run: |
        Write-Host "Running AL tests in container ${{ inputs.container-name }}..."

        if (-not $env:BC_USERNAME) { Write-Host "::error::BC_USERNAME is null"; exit 1 }
        if (-not $env:BC_PASSWORD) { Write-Host "::error::BC_PASSWORD is null"; exit 1 }

        try {
          $securePassword = ConvertTo-SecureString $env:BC_PASSWORD -AsPlainText -Force
          $credential = New-Object PSCredential($env:BC_USERNAME, $securePassword)

          Write-Host "Checking Test Suite: ${{ inputs.test-suite-name }}"
          Write-Host "Executing Run-TestsInBcContainer command..."

          $testResults = Run-TestsInBcContainer `
            -containerName "${{ inputs.container-name }}" `
            -testSuite "${{ inputs.test-suite-name }}" `
            -testCodeunit "*" `
            -credential $credential `
            -detailed

          if (-not $testResults) {
            Write-Host "::error::No test results found! Please check if tests were executed correctly."
            exit 1
          }

          # Debug Test Results
          Write-Host "=== Test Results Debug ==="
          Write-Output $testResults | Format-List

          # Manual JUnit XML output
          $xml = New-Object System.Xml.XmlDocument
          $testResultsNode = $xml.CreateElement("testsuites")
          $xml.AppendChild($testResultsNode) | Out-Null

          $testsuite = $xml.CreateElement("testsuite")
          $testsuite.SetAttribute("name", "AL Test Suite")
          $testsuite.SetAttribute("tests", $testResults.TestResults.tests)
          $testsuite.SetAttribute("failures", $testResults.TestResults.failures)
          $testsuite.SetAttribute("errors", "0")
          $testsuite.SetAttribute("time", $testResults.TestResults.time)
          $testResultsNode.AppendChild($testsuite) | Out-Null

          foreach ($result in $testResults.Results) {
              $testcase = $xml.CreateElement("testcase")
              $testcase.SetAttribute("classname", $result.TestCodeunit)
              $testcase.SetAttribute("name", $result.TestFunction)
              $testcase.SetAttribute("time", $result.Duration)

              if ($result.Result -ne "Success") {
                  $failure = $xml.CreateElement("failure")
                  $failure.SetAttribute("message", $result.Message)
                  $failure.InnerText = $result.Message
                  $testcase.AppendChild($failure) | Out-Null
              }

              $testsuite.AppendChild($testcase) | Out-Null
          }

          $outputPath = "${{ github.workspace }}/TestResults.xml"
          $xml.Save($outputPath)

          Write-Host "✅ Test Results Saved at $outputPath"

          if ($testResults.TestResults.failures -gt 0) {
            Write-Host "::error::$($testResults.TestResults.failures) test(s) failed"
            exit 1
          }

          Write-Host "✅ All tests passed! Total: $($testResults.TestResults.tests), Failures: $($testResults.TestResults.failures), Time: $($testResults.TestResults.time) sec"
        }
        catch {
          Write-Host "::error::Test execution failed!"
          Write-Host "::error::$_"
          exit 1
        }

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: al-test-results
        path: ${{ github.workspace }}/TestResults.xml
        retention-days: 30